apiVersion: v1
kind: Service
metadata:
  name: esme-service-lb
  namespace: esme-tp-klaraesme
spec:
  selector:
    app: esme-app          
  ports:
    - name: http
      port: 80             
      targetPort: 3000     
  type: LoadBalancer
