apiVersion: v1
kind: Service
metadata:
  name: esme-service
  namespace: esme-tp-klaraesme
spec:
  selector:
    app: esme-app          
  ports:
    - name: http
      port: 3000           
      targetPort: 3000     
  type: ClusterIP          
